name: Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: pwsh

env:
  IMAGE_NAME: alexmon1989/dripper

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macos-11, windows-2019 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set environment variables
        shell: bash
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      - name: Setup Python packages
        run: |
          python3 -m pip install -r requirements.test.txt
          python3 -m pip install pytest-github-actions-annotate-failures
          python3 -m pip install --upgrade pip -e .

      - name: Fast attack test
        if: runner.os == 'Linux'
        run: |
          dripper -t 1 -s https://httpbin.org:443 --dry-run

      - name: Run Tests with coverage
        run: python3 -m pytest tests/ -v

      - name: Run Benchmark
        run: python3 -m pytest tests/ -c pytest.benchmark.ini

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: runner.os == 'Linux'
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure Docker metadata
        if: runner.os == 'Linux'
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Login to Docker Hub
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: runner.os == 'Linux'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
          push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Docker Hub Description
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux'
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: ${{ env.IMAGE_NAME }}

      - name: Get the release version
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux'
        id: get-version
        run: |
          echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Prepare Release Notes
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux'
        run: |
          ./.github/release-notes.sh ./CHANGELOG.md > ./release-notes.md

      - name: Update Release notes
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.get-version.outputs.version }}
          tag: ${{ steps.get-version.outputs.version }}
          bodyFile: "./release-notes.md"
          allowUpdates: true

      - name: Fast attack test using Docker
        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux'
        run: |
          docker build -t alexmon1989/dripper:ci-test --no-cache --rm .
          docker run -i --rm alexmon1989/dripper:ci-test -t 1 -s https://httpbin.org:443 --dry-run
